name: Invitation to join Codinasion
description: I would like to be part of this awesome community
title: "Please invite me to Codinasion"
labels: [welcome 🎉🎉🎉]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
