name: Message From Community
description: Write a message to get featured on the codinasion.org Homepage
title: "[`Message`]: From [Your Name]"
labels: ["message-from-community"]
assignees:
  - harshraj8843
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your message with us. We will feature it on the homepage of codinasion.org

  - type: input
    id: name
    attributes:
      label: Name
      description: Name to be displayed with the message
      placeholder: ex. John Doe
    validations:
      required: true

  - type: textarea
    id: message
    attributes:
      label: Message
      description: Write your message here
      placeholder: ex. Hello There :)
    validations:
      required: true

  - type: checkboxes
    id: getfeatured
    attributes:
      label: Get Featured
      description: Check this box if you want to get featured on the homepage of codinasion.org
      options:
        - label: I want to get featured on the homepage of codinasion.org
          required: true
