name: Invite to Organization
on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    if: github.event.label.name == 'welcome' && github.repository == 'codinasion/.github'
    runs-on: ubuntu-latest

    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.4
        with:
          organization: Codinasion
          label: welcome
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: |
            Hey ${{ github.event.issue.user.login }}!

            **An invitation has been sent to you to join the GitHub Organisation. Welcome to the community :tada:**

            Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see.
            You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/codinasion/people

        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
